function weights = GetCEWeights(note)
if note >= 100 && note < 199
    % backup1, mean
    % 1.25s hPre and 1.75s hPost
elseif note >= 200 && note < 299
    % backup1, sum
    % 1.25s hPre and 1.75s hPost
elseif note >= 300 && note < 399
    % backup2, mean
    % 1.25s hPre and 1.75s hPost
elseif note >= 400 && note < 499
    % backup2, sum
    % 1.25s hPre and 1.75s hPost
end
    
switch mod(note,100)
    case 1 % original os
        weights = struct( ...
            "pos", 1, ...
            "posy", 0, ...
            "simTx", 1, ...
            "simMo", 0, ...
            "smth", 0, ...
            "cntr", 1);
    case 5
        weights = struct( ...
            "pos", 0, ...
            "posy", 0, ...
            "simTx", 1, ...
            "simMo", 0, ...
            "smth", 0, ...
            "cntr", 1);
    case 12
        weights = struct( ...
            "pos", 1, ...
            "posy", 0, ...
            "simTx", 1, ...
            "simMo", 0, ...
            "smth", 0, ...
            "cntr", 0);
    case 21
        weights = struct( ...
            "pos", 10, ...
            "posy", 0, ...
            "simTx", 10, ...
            "simMo", 0, ...
            "smth", 0, ...
            "cntr", 10);
    case 25
        weights = struct( ...
            "pos", 0, ...
            "posy", 0, ...
            "simTx", 10, ...
            "simMo", 0, ...
            "smth", 0, ...
            "cntr", 10);
    case 32
        weights = struct( ...
            "pos", 10, ...
            "posy", 0, ...
            "simTx", 10, ...
            "simMo", 0, ...
            "smth", 0, ...
            "cntr", 0);
end

if note >= 100 && note < 199
    weights.afloss = "mean";
elseif note >= 200 && note < 299
    weights.afloss = "sum";
elseif note >= 300 && note < 399
    weights.afloss = "mean";
elseif note >= 400 && note < 499
    weights.afloss = "sum";
end
end